services:
  web:
    build: .
    image: anguspllg/mcdocalorietracker:latest
    container_name: mcdo-calorie-tracker-web
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - ORIGIN=http://localhost:4173
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    ports:
      - '4173:3000'

  db:
    image: postgres
    container_name: mcdo-calorie-tracker-db
    ports:
      - '5432:5432'
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data:Z
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:Z

  redis:
    container_name: mcdo-calorie-tracker-redis
    image: redis:alpine
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - redis-data:/data

volumes:
  redis-data:
